### ISSUE TITLE
Add assert_lt, gt, le, ge functions

### ISSUE THREAD

**Issue by rosik** [tarantool/luatest#125] opened 2021-04-02 12:32 UTC
It's helpful sometimes. Copy-paste it from here: https://github.com/tarantool/cartridge/blob/98d616ae50304c42dd8e19dee92f4480e220c229/test/helper.lua#L135-L153

**Comment by olegrok** [comment] 2021-04-02 13:10
Seems like duplicate of https://github.com/tarantool/luatest/issues/76

**Comment by Steap2448** [comment] 2021-04-21 22:31
Closed via #126

**Closed by Steap2448** 2021-04-21 22:31 UTC
Labels: enhancement
